#!/bin/zsh
# PATH variables
export PATH=$PATH:$HOME/bin:/opt/cross/bin:$GOPATH/bin:$HOME/.cargo/bin:/usr/local/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"
export C_INCLUDE_PATH=$C_INCLUDE_PATH:"/usr/local/include"
export BXSHARE="$HOME/opt/bochs/share/bochs"

# Turn off tracking
export HOMEBREW_NO_ANALYTICS=1

# OpenGL Setup
export GLM_INCLUDE_DIR="/usr/local/Cellar/glm/0.9.8.3/include"
export GLFW_DIR=$HOME/lib/glfw-3.2.1
export GLEW_DIR="/usr/local/Cellar/glew/2.0.0"

# Git Aliases
alias gdiff="git diff"
alias gdiffm="git diff master"
alias gs="git status"

# General Aliases
function mkcd() {
	mkdir $1; cd $1
}
export mkcd
function follow() {
   $foo="$2."
   mv $1 $foo
   cd $2
}
function multi_print() {
    str=$1
    num=$2
    v=$(printf "%-${num}s" "$str")
    echo "${v// /$str}"
}
export multi_print

alias ls="ls --color=auto"
alias mktempdir="cd `mktemp -d`"
alias ta="tmux attach"
alias minix_boot='VBoxManage startvm "Minix" --type headless'
alias vbm="VBoxManage"
alias lockscreen='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
alias notes="grip notes.md &> /dev/null &"
