#!/bin/zsh
# PATH variables
export PATH=$PATH:$HOME/bin:/opt/cross/bin:$GOPATH/bin:$HOME/.cargo/bin:/usr/local/sbin:/usr/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include
export BXSHARE="$HOME/opt/bochs/share/bochs"
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export GOPATH=$HOME/go

# Turn off tracking
export HOMEBREW_NO_ANALYTICS=1

# FZF setup
export FZF_DEFAULT_OPTS='--multi --no-mouse'

# OpenGL Setup
export GLM_INCLUDE_DIR="/usr/local/Cellar/glm/0.9.8.3/include"
export GLFW_DIR=$HOME/lib/glfw-3.2.1
export GLEW_DIR="/usr/local/Cellar/glew/2.0.0"

# Less History Plz
export LESSHISTFILE=/dev/null

# Git Aliases
alias gdiff="git diff"
alias gdiffm="git diff master"
alias gs="git status"

# General Aliases
function mkcd() {
	mkdir $1; cd $1
}
export mkcd
function follow() {
   mv $1 $2
   if [ -d $2 ]; then
       cd $2
   else
       cd `dirname $2`
   fi
}
function multi_print() {
    str=$1
    num=$2
    v=$(printf "%-${num}s" "$str")
    echo "${v// /$str}"
}
export multi_print

if [[ `uname` == "Linux" ]]; then
    alias ls="ls --color=auto"
else
    alias ls="ls -G"
fi

alias mktempdir="cd `mktemp -d`"
alias vbm="VBoxManage"
alias lockscreen='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
alias rss='newsboat'
alias dev='vbm startvm Dev --type=headless; sleep 10; ssh dev'
